version: '3.4'
services:
  sql:
    image: mcr.microsoft.com/mssql/server:2017-CU20-ubuntu-16.04
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: '${DB_PASSWORD:-Password_123}'
      ACCEPT_EULA: 'Y'
    volumes:
      - 'dbdata:/var/opt/mssql'
    networks:
      net: null
  oracle:
    image: oracle/database:11.2.0.2-xe
    shm_size: 1g
    #volumes:
    #  - /home/oracle/oradata:/opt/oracle/oradata # persistent oracle database data.
    ports:
      - 1521:1521
      - 8080:8080
      - 5500:5500 
    networks:
      net: null
volumes:
  dbdata:
    driver: local
networks:
  proxy:
    driver: bridge
  net:
    driver: bridge
